USE [master]
GO
/****** Object:  Database [FCQ]    Script Date: 10/06/2025 04:57:55 p. m. ******/
CREATE DATABASE [FCQ]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FCQ', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\FCQ.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FCQ_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\FCQ_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [FCQ] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FCQ].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [FCQ] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [FCQ] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [FCQ] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [FCQ] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [FCQ] SET ARITHABORT OFF 
GO
ALTER DATABASE [FCQ] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [FCQ] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [FCQ] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [FCQ] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [FCQ] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [FCQ] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [FCQ] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [FCQ] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [FCQ] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [FCQ] SET  ENABLE_BROKER 
GO
ALTER DATABASE [FCQ] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [FCQ] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [FCQ] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [FCQ] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [FCQ] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [FCQ] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [FCQ] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [FCQ] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [FCQ] SET  MULTI_USER 
GO
ALTER DATABASE [FCQ] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [FCQ] SET DB_CHAINING OFF 
GO
ALTER DATABASE [FCQ] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [FCQ] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [FCQ] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [FCQ] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [FCQ] SET QUERY_STORE = ON
GO
ALTER DATABASE [FCQ] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [FCQ]
GO
/****** Object:  Table [dbo].[Historial]    Script Date: 10/06/2025 04:57:56 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Historial](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](255) NOT NULL,
	[Descripcion] [nvarchar](500) NULL,
	[Fecha] [date] NOT NULL,
	[Hora] [time](7) NOT NULL,
	[UsuarioId] [int] NOT NULL,
	[Archivo] [varbinary](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuarios]    Script Date: 10/06/2025 04:57:56 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuarios](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](50) NOT NULL,
	[PasswordHash] [nvarchar](255) NOT NULL,
	[Email] [nvarchar](100) NULL,
	[CreatedAt] [datetime] NULL,
	[Rol] [nvarchar](20) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Historial] ADD  DEFAULT (CONVERT([date],getdate())) FOR [Fecha]
GO
ALTER TABLE [dbo].[Historial] ADD  DEFAULT (CONVERT([time],getdate())) FOR [Hora]
GO
ALTER TABLE [dbo].[Usuarios] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[Usuarios] ADD  DEFAULT ('usuario') FOR [Rol]
GO
ALTER TABLE [dbo].[Historial]  WITH CHECK ADD FOREIGN KEY([UsuarioId])
REFERENCES [dbo].[Usuarios] ([Id])
GO
USE [master]
GO
ALTER DATABASE [FCQ] SET  READ_WRITE 
GO
